# 0: CPU, 1: NVIDIA
backend = 0

# 0: U16, 1: U32
dtype = 0

# ADM Threshold (Typical: 4000)
adm_threshold = 4000

# ---------------------------------------------------------
# ADM Compression Stage Thread Settings
# ---------------------------------------------------------

# Step 1: Center calculation
adm_center_calc_threads = 32
# Step 2: Encoding
adm_encode_threads = 32
# Step 3: Warp reduction
adm_warp_reduce_threads = 32
# Step 4: Fill tail bits
adm_fill_tail_threads = 32
# Step 5: Write back bit signals
adm_write_back_threads = 32

# ---------------------------------------------------------
# ADM Decompression Stage Thread Settings
# ---------------------------------------------------------

# Step 1: Restore signals
adm_restore_signals_threads = 32

# Step 2: Decode values
adm_decode_values_threads = 16