# 0: CPU, 1: NVIDIA
backend = 0

# 0: U16, 1: U32
dtype = 0

# 0: p-mode (ADM->PANS), 1: r-mode (ADM->FSE)
mode = 0

# Mapping dims (1/2/3D)
dims = 1
nx = 1048576
ny = 0
nz = 0

# ---------------------------------------------------------
# ADM Thread Settings
# ---------------------------------------------------------

# Shared thread count for all ADM compress stages
adm_compress_thread = 32

# Shared thread count for all ADM decompress stages
adm_decompress_thread = 16
